### ISSUE TITLE
Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by eka7a** [qaharmdz/opencart-shortcodes#12]
Example image shortcode
[image src="catalog/demo/compaq_presario.jpg" img_w="300" img_h="184" alt="compaq-presario-2014" align="center" /]

If PHP 7.1 is installed on the server, an error occurs.
Warning: A non-numeric value encountered in system/helper/shortcodes_default.php on line 364

**Comment by vannguyen0311** [comment]
Opencart Version 1.5.6.1 & vqmod 2.4.1 error Fatal error: Class 'Controller' not found in xxxx\system\helper\shortcodes_default.php on line 2

**Comment by vannguyen0311** [comment]
> 
> 
> Example image shortcode
> [image src="catalog/demo/compaq_presario.jpg" img_w="300" img_h="184" alt="compaq-presario-2014" align="center" /]
> 
> If PHP 7.1 is installed on the server, an error occurs.
> Warning: A non-numeric value encountered in system/helper/shortcodes_default.php on line 364

I am using Opencart Version 1.5.6.1 & vqmod 2.4.1 with the following error:
_Fatal error: Class 'Controller' not found in xxxx\system\helper\shortcodes_default.php on line 2__

**Comment by eka7a** [comment]
@vannguyen0311 
Not work OpenCart v1.5.6.1. OpenCart v2 required

Warning: A non-numeric value encountered #13
